# -*- coding: utf-8 -*-
"""Copy of FINAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVrD62Re8VUIBV4lxedE7nf123m8IPX8
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import librosa
import librosa.display
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (Input, Conv2D, MaxPooling2D, Dropout, LSTM, Bidirectional,
                                     BatchNormalization, Dense, Reshape, Layer)
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
import tensorflow.keras.backend as K

# --- 0. PATH CONFIGURATION ---
RAVDESS_PATH = '/content/drive/My Drive/RAVDESS'

if not os.path.exists(RAVDESS_PATH):
    print(f"Warning: The specified RAVDESS_PATH does not exist: {RAVDESS_PATH}")
    print("Please update the RAVDESS_PATH variable in the script.")
    os.makedirs(RAVDESS_PATH, exist_ok=True)

# --- 1. PARAMETERS ---
EMOTION_LABELS = {
    '03': 'happy', '04': 'sad', '05': 'angry', '06': 'fearful', '07': 'disgust', '08': 'surprised',
}
SAMPLE_RATE = 22050
N_FFT = 2048
HOP_LENGTH = 512
N_MELS = 128
FIXED_WIDTH = 256
EPOCHS = 200
PATIENCE_EARLY_STOP = 35 # Increased patience for stable learning
PATIENCE_LR_PLATEAU = 10
BATCH_SIZE = 32

# --- 2. DATA AUGMENTATION ---
def augment_data(audio, sr=SAMPLE_RATE):
    if np.random.rand() < 0.6:
        noise_factor = 0.05 * np.random.uniform() * np.amax(audio)
        return audio + noise_factor * np.random.randn(len(audio))
    else:
        stretch_rate = np.random.uniform(0.7, 1.3)
        stretched_audio = librosa.effects.time_stretch(y=audio, rate=stretch_rate)
        pitch_shift_steps = np.random.uniform(-4, 4)
        return librosa.effects.pitch_shift(y=stretched_audio, sr=sr, n_steps=pitch_shift_steps)

# --- 3. DATA LOADING ---
def load_data():
    X, y = [], []
    if not os.path.exists(RAVDESS_PATH) or not any(os.scandir(RAVDESS_PATH)):
        print(f"RAVDESS_PATH '{RAVDESS_PATH}' is empty or does not exist.")
        return np.array([]), np.array([])

    for dirname, _, filenames in os.walk(RAVDESS_PATH):
        for filename in sorted(filenames):
            if filename.endswith('.wav'):
                try:
                    emotion_code = filename.split('-')[2]
                    if emotion_code in EMOTION_LABELS:
                        file_path = os.path.join(dirname, filename)

                        spectrogram = extract_spectrogram(file_path, augment=False)
                        if spectrogram is not None:
                            X.append(spectrogram)
                            y.append(EMOTION_LABELS[emotion_code])

                        # Create 3 augmented versions
                        for _ in range(3):
                            spectrogram_aug = extract_spectrogram(file_path, augment=True)
                            if spectrogram_aug is not None:
                                X.append(spectrogram_aug)
                                y.append(EMOTION_LABELS[emotion_code])
                except IndexError:
                    print(f"Skipping file with unexpected format: {filename}")
    return np.array(X), np.array(y)

def extract_spectrogram(file_path, augment=False):
    try:
        # Load audio, ensuring it's not too long to avoid memory issues
        audio, sample_rate = librosa.load(file_path, sr=SAMPLE_RATE, duration=3.5, offset=0.5)
        if augment:
            audio = augment_data(audio, sr=sample_rate)

        spectrogram = librosa.feature.melspectrogram(y=audio, sr=sample_rate, n_mels=N_MELS, n_fft=N_FFT, hop_length=HOP_LENGTH)
        spectrogram_db = librosa.power_to_db(spectrogram, ref=np.max)

        if spectrogram_db.shape[1] > FIXED_WIDTH:
            spectrogram_db = spectrogram_db[:, :FIXED_WIDTH]
        else:
            spectrogram_db = np.pad(spectrogram_db, ((0, 0), (0, FIXED_WIDTH - spectrogram_db.shape[1])), mode='constant')

        return spectrogram_db[..., np.newaxis]
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return None

# --- 4. ATTENTION LAYER ---
class Attention(Layer):
    def __init__(self, **kwargs):
        super(Attention, self).__init__(**kwargs)

    def build(self, input_shape):
        self.W = self.add_weight(name="att_weight", shape=(input_shape[-1], 1), initializer="glorot_uniform")
        self.b = self.add_weight(name="att_bias", shape=(input_shape[1], 1), initializer="zeros")
        super(Attention, self).build(input_shape)

    def call(self, x):
        et = K.squeeze(K.tanh(K.dot(x, self.W) + self.b), axis=-1)
        at = K.softmax(et)
        at = K.expand_dims(at, axis=-1)
        output = x * at
        return K.sum(output, axis=1)

    def compute_output_shape(self, input_shape):
        return (input_shape[0], input_shape[-1])

# --- 5. MAIN SCRIPT ---
if __name__ == "__main__":
    print("Step 1: Loading and preprocessing data...")
    X_data, y_labels = load_data()

    if len(y_labels) == 0:
        print("No data loaded. Exiting.")
        exit()

    print(f"Loaded {len(X_data)} samples.")

    label_encoder = LabelEncoder()
    y_encoded = label_encoder.fit_transform(y_labels)

    # CRITICAL BUG FIX: The incorrect scaler that corrupted data has been removed.
    # Batch Normalization within the model will handle feature scaling correctly.

    X_train, X_test, y_train, y_test = train_test_split(
        X_data, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
    )

    input_shape = X_train.shape[1:]

    # --- 6. MODEL ARCHITECTURE ---
    print("Step 2: Building the definitive model...")
    l2_reg = 0.001

    model = Sequential([
        Input(shape=input_shape),
        Conv2D(64, (3, 3), activation='relu', padding='same', kernel_regularizer=l2(l2_reg)),
        BatchNormalization(),
        MaxPooling2D((3, 3), strides=(2, 2), padding='same'),
        Dropout(0.3),

        Conv2D(128, (3, 3), activation='relu', padding='same', kernel_regularizer=l2(l2_reg)),
        BatchNormalization(),
        MaxPooling2D((3, 3), strides=(2, 2), padding='same'),
        Dropout(0.3),

        Conv2D(256, (3, 3), activation='relu', padding='same', kernel_regularizer=l2(l2_reg)),
        BatchNormalization(),
        MaxPooling2D((3, 3), strides=(2, 2), padding='same'),
        Dropout(0.3),

        Reshape((32, 16 * 256)),

        Bidirectional(LSTM(128, return_sequences=True)),
        Attention(),

        Dense(128, activation='relu', kernel_regularizer=l2(l2_reg)),
        BatchNormalization(),
        Dropout(0.5),

        Dense(len(EMOTION_LABELS), activation='softmax')
    ])

    optimizer = Adam(learning_rate=0.0003) # Stable learning rate
    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    model.summary()

    # --- 7. TRAINING ---
    print(f"\nStep 3: Training the model...")
    callbacks = [
        EarlyStopping(monitor='val_accuracy', mode='max', patience=PATIENCE_EARLY_STOP, restore_best_weights=True, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=PATIENCE_LR_PLATEAU, min_lr=1e-7, verbose=1)
    ]

    history = model.fit(
        X_train, y_train,
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        validation_data=(X_test, y_test),
        callbacks=callbacks,
        verbose=1
    )

    # --- 8. EVALUATION ---
    print("\nStep 4: Evaluating the final model...")
    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)

    print(f"\n-------------------------------------------")
    print(f"Final Test Loss: {loss:.4f}")
    print(f"Final Test Accuracy: {accuracy*100:.2f}%")
    print(f"-------------------------------------------")

    # --- 9. PLOTTING ---
    plt.style.use('seaborn-v0_8-darkgrid')
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
    ax1.plot(history.history['accuracy'], label='Training Accuracy')
    ax1.plot(history.history['val_accuracy'], label='Validation Accuracy')
    ax1.set_title('Model Accuracy')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Accuracy')
    ax1.legend()

    ax2.plot(history.history['loss'], label='Training Loss')
    ax2.plot(history.history['val_loss'], label='Validation Loss')
    ax2.set_title('Model Loss')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Loss')
    ax2.legend()

    plt.tight_layout()
    plt.show()

# --- 10. DETAILED EVALUATION (F1, PRECISION, RECALL) ---
    from sklearn.metrics import classification_report, confusion_matrix
    import seaborn as sns

    print("\nStep 5: Generating detailed evaluation report...")
    # 1. Get predictions from the model
    y_pred_probs = model.predict(X_test)
    y_pred = np.argmax(y_pred_probs, axis=1)

    # 2. Get the names of the classes
    class_names = label_encoder.classes_
    # 3. Generate and print the classification report
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=class_names))

    # 4. Generate and plot the confusion matrix
    print("\nConfusion Matrix:")
    conf_matrix = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(10, 8))
    sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names)
    plt.title('Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()

import seaborn as sns
import matplotlib.pyplot as plt


print("Displaying dataset balance (Countplot)...")
plt.figure(figsize=(12, 6))
# We sort the labels alphabetically to ensure a consistent plotting order
sns.countplot(x=sorted(y_labels), hue=sorted(y_labels), palette='viridis', legend=False)
plt.title(f'Count of Samples per Emotion (Total = {len(y_labels)})', fontsize=16)
plt.ylabel('Number of Samples', fontsize=12)
plt.xlabel('Emotion', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import os
import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt


RAVDESS_PATH = '/content/drive/My Drive/RAVDESS'

# 2. Define the emotions
EMOTION_LABELS = {
    '03': 'Happy',
    '04': 'Sad',
    '05': 'Angry',
    '06': 'Fearful',
    '07': 'Disgust',
    '08': 'Surprised',
}

# 3. Define the spectrogram parameters
SAMPLE_RATE = 22050
N_FFT = 2048
HOP_LENGTH = 512
N_MELS = 128

def find_example_files(base_path, emotion_map):
    """Finds one file for each emotion."""
    emotion_files = {label: None for label in emotion_map.values()}
    emotions_needed = list(emotion_map.keys())

    if not os.path.exists(base_path):
        print(f"Error: Path does not exist: {base_path}")
        return {}

    for dirname, _, filenames in os.walk(base_path):
        for filename in sorted(filenames):
            if not filename.endswith('.wav'):
                continue

            try:
                parts = filename.split('-')
                emotion_code = parts[2]

                if emotion_code in emotions_needed:
                    label_name = emotion_map[emotion_code]
                    if emotion_files[label_name] is None:
                        emotion_files[label_name] = os.path.join(dirname, filename)
                        emotions_needed.remove(emotion_code)
                        print(f"Found '{label_name}' sample: {filename}")

                if not emotions_needed:
                    return emotion_files

            except IndexError:
                continue

    return emotion_files

def get_audio_and_spectrogram(file_path):
    """Loads audio, creates a waveform, AND creates a log-power Mel spectrogram."""
    try:
        audio, sr = librosa.load(file_path, sr=SAMPLE_RATE)

        spectrogram = librosa.feature.melspectrogram(
            y=audio,
            sr=sr,
            n_mels=N_MELS,
            n_fft=N_FFT,
            hop_length=HOP_LENGTH
        )
        spectrogram_db = librosa.power_to_db(spectrogram, ref=np.max)

        # Return all components
        return audio, sr, spectrogram_db

    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return None, None, None

# --- Main script execution ---
print("Scanning for example files...")
example_files = find_example_files(RAVDESS_PATH, EMOTION_LABELS)

if not any(example_files.values()):
    print("\nNo audio files were found. Please check your RAVDESS_PATH.")
else:
    print("\nGenerating waveplots and spectrograms...")


    fig, axes = plt.subplots(nrows=6, ncols=2, figsize=(16, 22))
    fig.suptitle('Waveplots and Spectrograms for Each Emotion', fontsize=20, weight='bold')

    for i, (emotion_name, file_path) in enumerate(example_files.items()):
        if file_path is None:
            print(f"Could not find file for {emotion_name}. Skipping plots.")
            axes[i, 0].set_title(f"{emotion_name}\n(File not found)")
            axes[i, 1].set_title(f"{emotion_name}\n(File not found)")
            axes[i, 0].axis('off')
            axes[i, 1].axis('off')
            continue


        audio, sr, s_db = get_audio_and_spectrogram(file_path)

        if audio is None:
            continue

        # --- PLOT 1: WAVEPLOT (Left Column) ---
        librosa.display.waveshow(y=audio, sr=sr, ax=axes[i, 0], color='blue')
        axes[i, 0].set_title(f"{emotion_name} - Waveplot", fontsize=14, weight='bold')
        axes[i, 0].set_ylabel('Amplitude')
        axes[i, 0].set_xlabel('Time (s)')

        # --- PLOT 2: SPECTROGRAM (Right Column) ---
        librosa.display.specshow(
            s_db,
            sr=sr,
            hop_length=HOP_LENGTH,
            x_axis='time',
            y_axis='mel',
            ax=axes[i, 1],
            cmap='viridis'
        )
        axes[i, 1].set_title(f"{emotion_name} - Spectrogram", fontsize=14, weight='bold')
        axes[i, 1].set_ylabel('Frequency (Hz)')
        axes[i, 1].set_xlabel('Time (s)')



    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

model.save('/content/drive/My Drive/emotion_recognition_model.keras')